<?php
/** Generated by wordpress/build-theme.mjs. */
return array(
  '404' => array(
    'styles' => array(
      'css/fonts.css',
      'css/variables.css',
      'css/reset.css',
      'css/global.css',
      'css/header.css',
      'css/footer.css',
      'css/pages/content.css',
      'css/shared-chrome.css',
      'css/contact-widget.css',
      'css/cta.css',
      'css/metrika.css'
    ),
    'scripts' => array(
      'js/menu.js',
      'js/contact-widget.js',
      'js/metrika.js'
    )
  ),
  'home' => array(
    'styles' => array(
      'css/fonts.css',
      'css/reset.css',
      'css/pages/home-perfect.css',
      'css/contact-widget.css',
      'css/cta.css',
      'css/metrika.css',
      'css/lead-success-modal.css'
    ),
    'scripts' => array(
      'js/menu.js',
      'js/accordion.js',
      'js/calculator.js',
      'js/leads.js',
      'js/home.js',
      'js/contact-widget.js',
      'js/metrika.js'
    )
  ),
  'catalog' => array(
    'styles' => array(
      'css/fonts.css',
      'css/reset.css',
      'css/pages/catalog.css',
      'css/shared-chrome.css',
      'css/contact-widget.css',
      'css/cta.css',
      'css/filter-states.css',
      'css/metrika.css'
    ),
    'scripts' => array(
      'js/menu.js',
      'js/catalog.js',
      'js/contact-widget.js',
      'js/metrika.js'
    )
  ),
  'installment' => array(
    'styles' => array(
      'css/fonts.css',
      'css/reset.css',
      'css/pages/installment.css',
      'css/shared-chrome.css',
      'css/contact-widget.css',
      'css/cta.css',
      'css/metrika.css'
    ),
    'scripts' => array(
      'js/menu.js',
      'js/accordion.js',
      'js/calculator.js',
      'js/contact-widget.js',
      'js/metrika.js'
    )
  ),
  'rent-to-own' => array(
    'styles' => array(
      'css/fonts.css',
      'css/reset.css',
      'css/pages/rent-to-own.css',
      'css/shared-chrome.css',
      'css/contact-widget.css',
      'css/cta.css',
      'css/metrika.css'
    ),
    'scripts' => array(
      'js/menu.js',
      'js/accordion.js',
      'js/contact-widget.js',
      'js/metrika.js'
    )
  ),
  'trade-in' => array(
    'styles' => array(
      'css/fonts.css',
      'css/reset.css',
      'css/pages/trade-in.css',
      'css/shared-chrome.css',
      'css/contact-widget.css',
      'css/cta.css',
      'css/metrika.css',
      'css/lead-success-modal.css'
    ),
    'scripts' => array(
      'js/menu.js',
      'js/accordion.js',
      'js/leads.js',
      'js/trade-form.js',
      'js/contact-widget.js',
      'js/metrika.js'
    )
  ),
  'selection' => array(
    'styles' => array(
      'css/fonts.css',
      'css/reset.css',
      'css/shared-chrome.css',
      'css/pages/selection.css',
      'css/contact-widget.css',
      'css/cta.css',
      'css/metrika.css'
    ),
    'scripts' => array(
      'js/menu.js',
      'js/accordion.js',
      'js/contact-widget.js',
      'js/metrika.js'
    )
  ),
  'application' => array(
    'styles' => array(
      'css/fonts.css',
      'css/reset.css',
      'css/shared-chrome.css',
      'css/contact-widget.css',
      'css/cta.css',
      'css/pages/application.css',
      'css/metrika.css',
      'css/lead-success-modal.css'
    ),
    'scripts' => array(
      'js/menu.js',
      'js/leads.js',
      'js/application.js',
      'js/contact-widget.js',
      'js/metrika.js'
    )
  ),
  'car' => array(
    'styles' => array(
      'css/fonts.css',
      'css/reset.css',
      'css/pages/car.css',
      'css/shared-chrome.css',
      'css/contact-widget.css',
      'css/cta.css',
      'css/metrika.css'
    ),
    'scripts' => array(
      'js/menu.js',
      'js/gallery.js',
      'js/contact-widget.js',
      'js/metrika.js'
    )
  ),
  'news' => array(
    'styles' => array(
      'css/fonts.css',
      'css/reset.css',
      'css/pages/news.css',
      'css/shared-chrome.css',
      'css/contact-widget.css',
      'css/cta.css',
      'css/filter-states.css',
      'css/metrika.css'
    ),
    'scripts' => array(
      'js/menu.js',
      'js/news.js',
      'js/contact-widget.js',
      'js/metrika.js'
    )
  ),
  'article' => array(
    'styles' => array(
      'css/fonts.css',
      'css/reset.css',
      'css/pages/article.css',
      'css/shared-chrome.css',
      'css/contact-widget.css',
      'css/cta.css',
      'css/metrika.css'
    ),
    'scripts' => array(
      'js/menu.js',
      'js/contact-widget.js',
      'js/metrika.js'
    )
  ),
  'reviews' => array(
    'styles' => array(
      'css/fonts.css',
      'css/reset.css',
      'css/pages/reviews.css',
      'css/shared-chrome.css',
      'css/contact-widget.css',
      'css/cta.css',
      'css/metrika.css'
    ),
    'scripts' => array(
      'js/menu.js',
      'js/reviews.js',
      'js/contact-widget.js',
      'js/metrika.js'
    )
  ),
  'faq' => array(
    'styles' => array(
      'css/fonts.css',
      'css/variables.css',
      'css/reset.css',
      'css/global.css',
      'css/header.css',
      'css/footer.css',
      'css/pages/home.css',
      'css/pages/content.css',
      'css/shared-chrome.css',
      'css/contact-widget.css',
      'css/cta.css',
      'css/faq-filter.css',
      'css/metrika.css'
    ),
    'scripts' => array(
      'js/menu.js',
      'js/accordion.js',
      'js/faq.js',
      'js/contact-widget.js',
      'js/metrika.js'
    )
  ),
  'contact' => array(
    'styles' => array(
      'css/fonts.css',
      'css/reset.css',
      'css/pages/contact.css',
      'css/shared-chrome.css',
      'css/contact-widget.css',
      'css/cta.css',
      'css/metrika.css',
      'css/lead-success-modal.css'
    ),
    'scripts' => array(
      'js/menu.js',
      'js/leads.js',
      'js/contact.js',
      'js/contact-widget.js',
      'js/metrika.js'
    )
  ),
  'privacy' => array(
    'styles' => array(
      'css/fonts.css',
      'css/variables.css',
      'css/reset.css',
      'css/global.css',
      'css/header.css',
      'css/footer.css',
      'css/shared-chrome.css',
      'css/pages/legal.css',
      'css/contact-widget.css',
      'css/metrika.css'
    ),
    'scripts' => array(
      'js/menu.js',
      'js/contact-widget.js',
      'js/metrika.js'
    )
  ),
  'personal-data-consent' => array(
    'styles' => array(
      'css/fonts.css',
      'css/variables.css',
      'css/reset.css',
      'css/global.css',
      'css/header.css',
      'css/footer.css',
      'css/shared-chrome.css',
      'css/pages/legal.css',
      'css/contact-widget.css',
      'css/metrika.css'
    ),
    'scripts' => array(
      'js/menu.js',
      'js/contact-widget.js',
      'js/metrika.js'
    )
  )
);
